name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      # - name: Lint code
      #   run: pylint src/*.py
      - name: Run tests
        run: pytest src/test.py

  build-push-docker:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ca-housing-mlops-project:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ca-housing-mlops-project:latest
